### ISSUE TITLE
Set up a Kanban board 

### ISSUE THREAD

**Issue by ankitt26** [ankitt26/Second-Capstone-project#21]
### "We are a team of 2 people working on this project."

- The group task is assigned to - _@ankitt26_ 
- Student A - _@ankitt26_ 
- student B - _@Unleashedicon_

**Link of the project -**: https://github.com/ankitt26/capston-2/projects/1

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Correct project table ✔️ 
- Good implementations ✔️ 

## Required Changes ♻️
- [x] [REQUIRED] Good job so far! Kindly you forgot to `assign` `Solo` and `Group` tasks please implement all of them 🙏🏼 

![image](https://github.com/ankitt26/capston-2/assets/63915024/95f4006d-7eaa-455c-a46a-c15eab090af8)  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ankitt26** [comment]
Thanks for reviewing🙏🏿.

**Comment by andersonlebon** [comment]
## Hi @team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ankitt26** [comment]
Thanks for reviewing 🙏🏿.
